### ISSUE TITLE
should status be checking `status/all` instead of `status`

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sdr-deploy#16]
the web status check is going to `status` but I'm wondering if it should be going to `status/all`  (https://github.com/sul-dlss/sdr-deploy/blob/master/deploy.rb#L104)

**Comment by justinlittman** [comment]
Many of our `status/all` checks are broken. (I nominated fixing this for the last patch party, but it didn't make the cut; however, still think it would be very valuable to rectify.)

**Comment by ndushay** [comment]
This is done.  See repos.yml
