### ISSUE TITLE
Generate Reports 

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/sdr-deploy#33]
In the current First Responder workflow, we are creating a new tab in the dependency update spreadsheet for all of the open PRs to update dependencies for our Ruby and JS based projects. It seems like we could generate a report (text or even just a csv file) that provides this information instead of requiring manual copy-pasting-manual updating by the FR.

**Comment by mjgiarlo** [comment]
Given we are no longer using the spreadsheet to manage weekly updates, do you reckon we could close this, @jermnelson ?
