### ISSUE TITLE
[spike] try using an SSH tunnel to hit status pages

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/sdr-deploy#38]
The deployment script can't hit some status pages it wants to use for post-deployment success checks, because some status pages only allow connections from whitelisted VMs (which host connecting services) or from webauthed browser sessions.

One way around this (suggested by @jcoyne) would be to make a request to the status page by way of tunneling through the VM to which deployment is happening, since the VM should be allowed to make requests to itself.

For this ticket, the spike is to experiment with an approach like:
1. before the status check, create an SSH tunnel to the server being status checked
2. request the okcomputer status page via the SSH tunnel that was just created
3. tear down the tunnel
4. repeat per status page to be checked

alternate approach that would obviate need for https://github.com/sul-dlss/operations-tasks/issues/2301, which was filed because of inability to hit these status pages from terminal after running the deploy script:
* https://sul-suri-prod.stanford.edu/status
* https://workflow-service-prod.stanford.edu/workflow/status
* https://workflow-service-qa.stanford.edu/workflow/status
* https://workflow-service-stage.stanford.edu/workflow/status
* https://sul-suri-qa.stanford.edu/status
* https://sul-suri-stage.stanford.edu/status

**Comment by peetucket** [comment]
one potential lead for tunneling: https://github.com/net-ssh/net-ssh-gateway 

after a couple quick attempts ... haven't gotten it to work just yet, may not be understanding the authentication

**Comment by mjgiarlo** [comment]
@peetucket @jmartin-sul Y'all think we should keep this issue around or has its time passed?

**Comment by peetucket** [comment]
🤷 It might still be nice to have an "all-automatic" status check approach, but its certainly not a high priority, as SSHing into the machines manually to check is not very time consuming.   Another possible approach could be a single web page running a VM that just does all the checks to all of the servers (which is has access to of course), and then we hit that for a complete health check conformation.  But this also feels pretty low priority.

**Comment by mjgiarlo** [comment]
Since capistrano already has an ssh connection open to each box, we essentially already have the tunnel set up. So if we have a capistrano task as follows:

```ruby
namespace :deploy do
  after :finished, :check_status do
    on roles(:web) do |host|
      status_response = capture("curl https://#{host}/status/all")
      puts "Status check from #{host}:\n#{status_response}"
    end
  end
end
```

We can get a status check even on locked-down boxes. E.g., with `sul-suri-prod`:

```shell
$ cap prod deploy:check_status
Status check from sul-suri-prod.stanford.edu:
Default Collection
  database: PASSED Schema version: 20170825145538 (0.002s)
  default: PASSED Application is running (0.000s)
```

Before I slap any code in place for this, though, I want to wait until next dev planning when we are discussing how/when to do status checks.

**Comment by mjgiarlo** [comment]
Now that we have the `check_status` cap task, I'm closing this issue.
