### ISSUE TITLE
--check-cocina behavior triggered automatically before deploy

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/sdr-deploy#52]
Modify `deploy.rb` to perform the `--check-cocina` behavior automatically before deployment, so that it happens implicitly as part of the weekly dependency update process.

If an inconsistency in the cocina-models version is found among consumers of the gem, halt the script with an informative error message (and do not proceed with deployment).

~~As part of this, we can also get rid of the explicit reading of the `--check-cocina` arg, and the corresponding usage note at the top of the file.~~

**Comment by jermnelson** [comment]
@jmartin-sul, regarding the last requirement,
>  we can also get rid of the explicit reading of the --check-cocina arg, and the corresponding usage note at the top of the file.

Are you saying that we should totally remove the `--check-cocina` argument entirely? I think other devs liked being able to run just the cocina checking through the deploy script and would advocating keeping this option.

**Comment by jmartin-sul** [comment]
> @jmartin-sul, regarding the last requirement,
> 
> > we can also get rid of the explicit reading of the --check-cocina arg, and the corresponding usage note at the top of the file.
> 
> Are you saying that we should totally remove the `--check-cocina` argument entirely? I think other devs liked being able to run just the cocina checking through the deploy script and would advocating keeping this option.

good point, hadn't considered that!  struck that part of the description.
