### ISSUE TITLE
There should be a way to tag a set of repos

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-deploy#76]
After you run check_cocina and it results in a single version, there should be a way to tag every repo with a consistent version tag (e.g. "rel-88").  This tag will later be used to deploy a known good set of dependencies.

**Comment by mjgiarlo** [comment]
@jcoyne Sounds simple enough. A couple questions:

* Should the created tag be pushed to remotes or is a local tag sufficient?
* Should this always create a tag for every repo configured, or should this command include the `--only`/`--except` functionality?

**Comment by jcoyne** [comment]
> Should the created tag be pushed to remotes or is a local tag sufficient?
I think we want it to be remote so that the first-responder for next week could rollback to what you deployed this week.

> Should this always create a tag for every repo configured, or should this command include the --only/--except functionality?
I don't know

> Should it allow the user to skip the repo update or not?
Can you think of a reason someone would want to skip it?

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> 
> I think we want it to be remote so that the first-responder for next week could rollback to what you deployed this week.

Sounds good.
 
> > Should this always create a tag for every repo configured, or should this command include the --only/--except functionality?
> 
> I don't know

I'll leave it out for now.
 
> > Should it allow the user to skip the repo update or not?
> 
> Can you think of a reason someone would want to skip it?

Impatience? I'll leave it out.

thanks!
